version: "3.1"
services: 
  db: 
    image: postgres:11-alpine
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root"]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=todoservice
      - APP_DB_PASS=todoservice
      - APP_DB_NAME=todoservice
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    networks:
      - api.network
    deploy:
      resources:
        limits:
          memory: '512M'
          cpus: '1'
  api:
    build: .
    links:
      - db
    depends_on: 
      - db
    environment:
      SERVER.HOST: 0.0.0.0
      SERVER.PORT: 5000
      PG.USER: todoservice
      PG.PASSWORD: todoservice
      PG.HOST: db
      PG.PORT: 5432
      PG.DBNAME: todoservice
      PG.POOL.MAX_SIZE: 30
    deploy:
      replicas: 3
      resources:
        limits:
          memory: '1G'
          cpus: '1'
    ports:
      - 5000
    networks:
      - api.network
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: 
      - api
    ports:
      - 80:80
    networks:
      - api.network
networks:
  api.network:
    driver: bridge