GET http://localhost/ HTTP/1.1
###
GET http://localhost/todos HTTP/1.1
###
GET http://localhost/todos/1/items HTTP/1.1
###
PUT http://localhost/todos/1/items/2 HTTP/1.1
Conten-Type: application/json

{"success": false}
###
POST http://localhost:8080/todos HTTP/1.1
Content-Type: application/json

{"title": "List 3"}